apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- base/gateway.yaml
- base/auth-service.yaml
- base/data-service.yaml
- minio-secret.yaml
- minio-deployment.yaml
- data-service-sa.yaml