apiVersion: v1
kind: Pod
metadata:
  name: test-data-access
  namespace: application
spec:
  serviceAccountName: data-service-sa
  containers:
  - name: test
    image: amazon/aws-cli:latest
    command: ["sleep", "3600"]
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: accesskey
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: minio-credentials
          key: secretkey
    - name: S3_ENDPOINT
      value: "http://minio.application.svc.cluster.local:9000"
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
